<?php
include 'include.php';

define('APPLICATION_ID', '1139880209093500968');
define('INTERACTION_TOKEN', 'aW50ZXJhY3Rpb246MTE0MDIzOTE1NTA0MTkzOTQ5NjpTeTBEbHhicEZ1ZXRabVJ0UlczSUFlelVRYnI4cjREZU03b1hjckRlbHRKc2VnWmoxbW4xWGdXc3M1dmVraWJkZllBSHZpWmFVN1g5ang3M0xtZGN5bDQyRVUyblhJWlRQNGxkRmExSW55UUFwUWIwdEF0MnNWWEZrYnk5YXdhYg');

$url = "https://discord.com/api/webhooks/" . APPLICATION_ID . "/" . INTERACTION_TOKEN . "/messages/@original";
// $url = "https://discord.com/api/webhooks/" . APPLICATION_ID . "/" . INTERACTION_TOKEN . "/messages/1140222646915715092";
$url = "https://discord.com/api/webhooks/" . APPLICATION_ID . "/" . INTERACTION_TOKEN . "";

// Get the MP3 file content and encode it in base64
$mp3_content = file_get_contents("https://easyaivoice.com/i.mp3");
$mp3_base64 = base64_encode($mp3_content);

// random mp3 filename with timestamp
$rand = rand(1000, 9999) . "-" . time();
$mp3_filename = $rand . ".mp3";

// Create a file object with the name and content fields
$file = array(
    "name" => $mp3_filename,
    "content" => $mp3_base64
);

// Create an embed object with the title, description, and url fields
// $embed = array(
//     "title" => "Your audio file is ready",
//     "description" => "Click on the link below to listen to it",
//     "type" => "link",
//     "url" => "attachment://" . $mp3_filename
// );
$embed = array(
    "type" => "audio",
    "url" => "https://easyaivoice.com/i.mp3",
    "title" => "Easy AI Voice",
    "description" => "A sample audio file generated by Easy AI Voice",
    "color" => 16711680 // red

);


// Create a payload with the file and embeds parameters
$payload = array(
    "content" => "Your file is ready!",
    "embeds" => array(
        "type" => "audio",
        "url" => "https://easyaivoice.com/i.mp3",
        "title" => "Easy AI Voice",
        "description" => "A sample audio file generated by Easy AI Voice",
        "color" => 16711680 // red

    )
);
// "username" => "Tycoon69",
//     "avatar_url" => "https://cdn.discordapp.com/avatars/810919246744780840/3d2e26d8c15a387a5c6d4d14f08c5fd7.png?size=4096",
//"embeds" => array($embed),


$response = array(
    "content" => "Your audio file is ready",
    "embeds" => array(
        array(
            "type" => "audio",
            "url" => "https://easyaivoice.com/i.mp3",
            "title" => "Easy AI Voice",
            "description" => "A sample audio file generated by Easy AI Voice",
            "color" => 16711680 // red
        )
    )
);


// Get the binary data of the mp3 file
// $mp3_content = file_get_contents("https://easyaivoice.com/i.mp3");

// $response = array(
//     "content" => "Your audio file is ready",
//     // Add the file field with the mp3 data and filename
//     "file" => array(
//         "data" => $mp3_content,
//         "filename" => "i.mp3"
//     ),
//     // Add the embeds field with a preview of the audio file
//     "embeds" => array(
//         array(
//             "type" => "audio",
//             // Use attachment:// protocol to reference the file
//             "url" => "attachment://i.mp3",
//             "title" => "Easy AI Voice",
//             "description" => "A sample audio file generated by Easy AI Voice",
//             "color" => 16711680 // red
//         )
//     )
// );
$ch = curl_init($url);

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
// curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($response));
// curl_setopt($ch, CURLOPT_HTTPHEADER, array(
//     'Content-Type: multipart/form-data'
// ));



// $mp3_content = file_get_contents("https://easyaivoice.com/i.mp3");

// $response = array(
//     "content" => "Your audio file is ready",
//     // Add the embeds field with a preview of the audio file
//     "embeds" => array(
//         array(
//             "type" => "audio",
//             // Use attachment:// protocol to reference the file
//             "url" => "attachment://i.mp3",
//             "title" => "Easy AI Voice",
//             "description" => "A sample audio file generated by Easy AI Voice",
//             "color" => 16711680 // red
//         )
//     )
// );

// // Encode the message data as JSON
// $payload_json = json_encode($response);

// // Create a boundary string for the multipart request
// $boundary = '--------------------------' . microtime(true);

// // Build the header with the content type, file name and size
// $header = 'Content-Disposition: form-data; name="file"; filename="i.mp3"' . "\r\n";
// $header .= 'Content-Type: audio/mpeg' . "\r\n";
// $header .= 'Content-Length: ' . strlen($mp3_content) . "\r\n";
// $header .= "\r\n";

// // Build the body with the boundary, header, file data, and message data
// $body = '--' . $boundary . "\r\n";
// $body .= $header;
// $body .= $mp3_content;
// $body .= "\r\n";
// $body .= '--' . $boundary . "\r\n";
// $body .= 'Content-Disposition: form-data; name="payload_json"' . "\r\n";
// $body .= "\r\n";
// $body .= $payload_json;
// $body .= "\r\n";
// $body .= '--' . $boundary . "--\r\n";

// $ch = curl_init($url);

// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// curl_setopt($ch, CURLOPT_POST, true);
// curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
// curl_setopt($ch, CURLOPT_HTTPHEADER, array(
//     'Content-Type: multipart/form-data; boundary=' . $boundary
// ));





curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($response, JSON_UNESCAPED_SLASHES));
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json'
));

// $ch = curl_init($url);

// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// curl_setopt($ch, CURLOPT_POST, true);
// curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
// curl_setopt($ch, CURLOPT_HTTPHEADER, array(
//     'Content-Type: application/json'
// ));

$response = curl_exec($ch);

echo $response;
curl_close($ch);



// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PATCH");
// curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
// curl_setopt($ch, CURLOPT_HTTPHEADER, array(
//     'Content-Type: application/json'
// ));
